title: Enterprise AI Solutions
description: Production-ready AI automation templates built on Microsoft's enterprise framework
url: "https://maree217.github.io"
baseurl: "/enterprise-ai-solutions"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Company information
company:
  name: "Enterprise AI Solutions"
  tagline: "From Prototype to Production in Days, Not Months"
  email: "info@yourcompany.com"
  phone: "+44 (0) 20 7xxx xxxx"

# Social links
github_username: maree217
linkedin_username: your-linkedin

# Google Analytics
google_analytics: UA-XXXXXXXXX-X